[project]
name = "boids"
version = "1.5.1"
description = "Python Boids Simulation"
authors = [
    { name = "Akasha Mouginot", email = "akasha.mouginot@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = ["pygame-ce>=2.5.8",
                "click>=8.4",
                "akashic-perflogger>=0.2"]

[project.urls]
Repository = "https://github.com/ewigael/boids"
Issues = "https://github.com/ewigael/boids/issues"
Changelog = "https://github.com/ewigael/boids/blob/main/docs/CHANGELOG.md"
Readme = "https://github.com/ewigael/boids/blob/main/README.md"

[project.scripts]
boids = "boids.main:main"

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
